# Generated by Django 6.0.6 on 2026-07-06 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_chefs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chefs',
            old_name='twitter_url',
            new_name='linkedin_url',
        ),
    ]
