# Generated by Django 6.0.6 on 2026-07-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_twitter_url_chefs_linkedin_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefs',
            name='experience',
            field=models.CharField(max_length=50),
        ),
    ]
