# Generated by Django 6.0.6 on 2026-07-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_reservation_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=89)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('subject', models.CharField(choices=[('General Inquiry', 'General Inquiry'), ('Catering & Events', 'Catering & Events'), ('Feedback', 'Feedback'), ('Partnership', 'Partnership'), ('Media & Press', 'Media & Press')], default='General Inquiry', max_length=550)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
