# Generated by Django 6.0.6 on 2026-07-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Replied', 'Replied')], default='Pending', max_length=20),
        ),
    ]
